# Recipes for Potions
# name: Different names for bad/normal/good (Formatting codes possible: such as &6)
# ingredients: List of material/amount
# cookingtime: Time in real minutes ingredients have to boil
# distillruns: How often it has to be distilled for full alcohol (0=without distilling)
# wood: Wood of the barrel 0=any 1=Birch 2=Oak 3=Jungle 4=Spruce
# age: Time in Minecraft-days, the potion has to age in a barrel 0=no aging
# color: Color of the potion after distilling/aging. DARK_RED, RED, BRIGHT_RED, ORANGE, PINK, BLUE, CYAN, WATER, GREEN, BLACK, GREY, BRIGHT_GREY
# difficulty: 1-10 accuracy needed to get good quality (1 = unaccurate/easy, 10 = very precise/hard)
# alcohol: Absolute amount of alcohol 0-100 in a perfect potion (will be added directly to the player, where 100 means fainting)
# effects: List of effect/duration  Special potion-effect when drinking, duration in sek. Suffix name with 'X' to hide effect from label. Sample: POISONX/10
#   (WEAKNESS, INCREASE_DAMAGE, SLOW and SPEED are always hidden.)  Possible Effects: http://jd.bukkit.org/rb/apidocs/org/bukkit/potion/PotionEffectType.html
#   instant effects (such as HEAL) _must!_ have defined the level instead of the duration!
recipes:
   1:
      name: Skunky Wheatbeer/Wheatbeer/Fine Wheatbeer
      ingredients: 
      - WHEAT/3
      cookingtime: 8 minutes
      distillruns: 0
      wood: Birch      
      age: 2 mc days
      color: BRIGHT_GREY
      difficulty: 1
      alcohol: 5
   2:
      name: Skunky Beer/Beer/Fine Beer
      ingredients: 
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: any
      age: 3 mcd
      color: ORANGE
      difficulty: 1
      alcohol: 6
   3:
      name: Skunky Darkbeer/Darkbeer/Fine Darkbeer
      ingredients: 
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: 4
      age: 8
      color: BLACK
      difficulty: 2
      alcohol: 7
   4:
      name: Awkward Mead/Mead/ &6Golden Mead
      ingredients: 
      - SUGAR_CANE/6
      cookingtime: 3
      distillruns: 0
      wood: 2
      age: 4
      color: ORANGE
      difficulty: 2
      alcohol: 9
   5:
      name: Apple Wine/Sweet Apple Wine/ &6Golden Apple Wine
      ingredients: 
      - SUGAR_CANE/6
      - APPLE/2
      cookingtime: 4
      distillruns: 0
      wood: 2
      age: 4
      color: ORANGE
      difficulty: 4
      alcohol: 12
   6:
      name: Bitter Rum/Spicy Rum/&6Golden Rum
      ingredients: 
      - SUGAR_CANE/14
      cookingtime: 5
      distillruns: 2
      wood: 2
      age: 14
      color: DARK_RED
      difficulty: 6
      alcohol: 30
   7:
      name: Lousy Wood grain Alcohol/Wood grain Alcohol/Strong Wood grain Alcohol
      ingredients: 
      - POTATO_ITEM/10
      cookingtime: 15
      distillruns: 3
      age: 0
      color: BRIGHT_GREY
      difficulty: 4
      alcohol: 20
      effects:
      - WEAKNESS/15
      - POISON/10
   8:
      name: Poor Absinthe/Absinthe/&6Strong Absinthe
      ingredients:
      - LONG_GRASS/15
      cookingtime: 3
      distillruns: 6
      color: GREEN
      difficulty: 8
      alcohol: 45
      effects:
      - POISON/20t
   9:
      name: Potato soup
      ingredients:
      - POTATO_ITEM/5
      - LONG_GRASS/3
      cookingtime: 3
      color: PINK
      difficulty: 1
      effects:
      - HEAL/1
   10:
      name: Bad Skutten/Skutten/&6Fine Skutten
      ingredients: 
      - ROTTEN_FLESH/13
      cookingtime: 10
      distillruns: 2
      wood: 4
      age: 8
      color: RED
      difficulty: 4
      alcohol: 10
      effects:
      - POISON/10
   11:
      name: Bad Pumpkin Beer/Pumpkin Beer/&6Glissen Pumpkin Beer
      ingredients: 
      - PUMPKIN/20
      cookingtime: 20
      distillruns: 0
      wood: 0
      age: 14
      color: Gold
      difficulty: 5
      alcohol: 15
      effects:
      - INCREASE_DAMAGE/60
   12:
      name: Rut Gut/Mutter’s Milk/Mother’s Milk
      ingredients: 
      - COOKED_BEEF/6
      - CARROT_ITEM/4
      - SUGAR_CANE/2
      - MILK_BUCKET/1
      cookingtime: 10
      distillruns: 0
      wood: 3
      age: 7
      color: White
      difficulty: 5
      alcohol: 5
      effects:
       - REGENERATION/30
       - SATURATION/50
   13:
      name: Lousy Burbon/Burbon/Fine Burbon
      ingredients: 
      - SUGAR_CANE/3
      - WHEAT/3
      cookingtime: 10
      distillruns: 3
      wood: 4
      age: 14
      color: Dark_Grey
      difficulty: 3
      alcohol: 15
      effects:
      - CONFUSION/15
   14:
      name: Rotten Dragon/Dragon/Red Dragon
      ingredients: 
      - MAGMA_CREAM/1
      - BLAZE_POWDER/1
      - WHEAT/6
      - REDSTONE/5
      cookingtime: 10
      distillruns: 3
      wood: 3
      age: 10
      color: RED
      difficulty: 10
      alcohol: 25
      effects:
      - SPEED/180
      - FIRE_RESISTANCE/60
      - INCREASE_DAMAGE/60
   15:
      name: Rotten Grain/Grain Beer/Fine Grain Beer
      ingredients: 
      - SEEDS/10
      cookingtime: 20
      distillruns: 3
      wood: 0
      age: 10
      color: Green
      difficulty: 1
      alcohol: 20
   16:
      name: Nectar/Golden Nectar/Nectar of the Gods
      ingredients: 
      - GOLDEN_APPLE/1
      - WHEAT/15
      - SUGAR_CANE/15
      - GOLD_NUGGET/5
      cookingtime: 60
      distillruns: 4
      wood: 0
      age: 20
      color: Gold
      difficulty: 10
      alcohol: 30
      Effects:
        - INCREASE_DAMAGE/120
        - REGENERATION/120
        - ABSORPTION/120
        - FIRE_RESISTANCE/120
   17:
      name: Bad Tops/Tops brew/Fine Tops Brew
      ingredients: 
      - BROWN_MUSHROOM/10
      cookingtime: 5
      distillruns: 0
      wood: 3
      age: 8
      color: Red
      difficulty: 3
      alcohol: 25
      Effects:
         - SPEED/60
         - CONFUSION/15
   18:
      name: Rotten Eye/Eye's Brew/Fine Eye's Brew
      ingredients: 
      - SPIDER_EYE/8
      cookingtime: 15
      distillruns: 2
      wood: 4
      age: 5
      color: Grey
      difficulty: 5
      alcohol: 15
      Effects:
            -NIGHT_VISION/240
            -HUNGER/30
   19:
      name: Bad Gloom/Gloom Brew/Fine Gloom Brew
      ingredients: 
      - MELON/30
      cookingtime: 8
      distillruns: 2
      wood: 0
      age: 10
      color: Water
      difficulty: 8
      alcohol: 50
      Effects:
         -SPEED/60
         -BLINDNESS/60
         -INCREASE_DAMAGE/60
   20:
      name: Rocks/Bolders/Juggernaut
      ingredients: 
      - IRON_INGOT/5
      - WHEAT/10
       -MAGMA_CREAM/10
      cookingtime: 30
      distillruns: 5
      wood: 4
      age: 20
      color: Black
      difficulty: 8
      alcohol: 25
      Effects:
        -INCREASE_DAMAGE/60
        -SLOW/60
        -DAMAGE_RESISTANCE/60
   21:
      name: Bad Gold Schlogger/Gold Schlogger/Fine Gold Schlogger
      ingredients: 
      - GOLD_NUGGET/5
      - SUGAR/15
      - MELON/5
      cookingtime: 18
      distillruns: 5
      wood: 0
      age: 17
      color: Cyan
      difficulty: 8
      alcohol: 20
      Effects:
         -INCREASE_DAMAGE/60
         -FAST_DIGGING/60
   22:
      name: Bad Gin/Gin/Fine Gin
      ingredients: 
      - SUGAR_CANE/10
      - POTATO_ITEM/25
      cookingtime: 18
      distillruns: 3
      wood: 0
      age: 8
      color: Water
      difficulty: 6
      alcohol: 10
   23:
      name: Bad Tequila/Tequila/Blue Tequila
      ingredients: 
      - INK_SACK/10
      cookingtime: 15
      distillruns: 3
      wood: 2
      age: 19
      color: Water
      difficulty: 8
      alcohol: 20
   24:
      name: Salty Marrow/Marrow/Dragon Marrow
      ingredients: 
      - BONE/3
      - INK_SACK/3
      cookingtime: 8
      distillruns: 0
      wood: 0
      age: 6
      color: White
      difficulty: 8
      alcohol: 15
      Effects:
         -INVISIBILITY/180
         -HUGER/30
   25:
      name: Uknown/Dangerous Brew/XXX      
      ingredients: 
      - RAW_FISH/6
      - RED_MUSHROOM/6
      - EYE_OF_ENDER/6
      cookingtime: 60
      distillruns: 6
      wood: 0
      age: 6
      color: water
      difficulty: 9
      alcohol: 100
      Effects:
         -HARM/50
         -POSION/50
         -HUNGER/100
         -INVISIBILITY/15
   26:
      name: bad Juice/ Juice/Rich Juice
      ingredients: 
      - SUGAR/15
      - MELON/5
      cookingtime: 3
      distillruns: 1
      wood: 0
      age: 0
      color: pink
      difficulty: 2
      alcohol: 5
      Effects:
         -SATURATION/30
   27:
      name: Poison puffer/Puffer/Wonderful Puffer
      ingredients: 
      - RAW_FISH/13
      cookingtime: 5
      distillruns: 1
      wood: 0
      age: 2
      color: Blue
      difficulty: 3
      alcohol: 10
      Effects:
         -WATER_BREATHING/150
         -NIGHT_VISION/120
   28:
      name: Bad Patriot/Patriot/Fantastic Patriot
      ingredients: 
      - INK_SACK/5
      - COOKED_BEEF/5
      - GRILLED_PORK/3
      cookingtime: 10
      distillruns: 7
      wood: 4
      age: 3
      color: red
      difficulty: 5
      alcohol: 25
      Effects:
         -INCREASE_DAMAGE/60
         -SPEED/60
         -WITHER/30
   29:
      name:  Bad Prarie Oyster/Prarie Oyster/Good Prarie Oyster
      ingredients: 
      - GRILLED_PORK/6
      - EGG/4
      - REDSTONE/2
      cookingtime: 5
      distillruns: 1
      wood: 0
      age: 0
      color: Red
      difficulty: 2
      alcohol: 5
      Effects:
         - HEAL/15
         - HUNGER/30
   30:
      name: Bad 30/30/Super 30
      ingredients: 
      - MELON/5
      - CARROT_ITEM/5
      - POTATO_ITEM/5
      - SUGAR/10
      - WHEAT/5
      cookingtime: 9
      distillruns: 6
      wood: 3
      age: 3
      color: Cyan
      difficulty: 6
      alcohol: 30
      Effects:
         -SPEED/90
         -HASTE/60
         -CONFUSION/30
         
# cooked: EVERY possible ingredient and the names for the originating potions after fermenting:

cooked:
   WHEAT: Fermented wheat
   SUGAR_CANE: Sugar brew
   APPLE: Apple cider
   POTATO_ITEM: Potatomash
   LONG_GRASS: Boiled herbs
   RED_MUSHROOM: Mushroom brew
   MAGMA_CREAM: Boiling brew
   BLAZE_POWDER: Steaming mash
   REDSTONE: Glowing soup
   COOKED_BEEF: Beefy stock
   MILK_BUCKET: Milky brew
   SUGAR: Sweat water
   ROTTEN_FLESH: Rotten mash
   SEEDS: Grassy Slury
   GOLDEN_APPLE: Heavenly cider
   GOLD_NUGGET: Golden mash
   BROWN_MUSHROOM: Murky mushroom brew
   SPIDER_EYE: Corrupted water
   MELON: Sweatened mash
   IRON_INGOT: Strong brew
   INK_SACK: Dyed brew
   BONE: Necrotic vial
   RAW_FISH : Fishy mash
   EYE_OF_ENDER: Mysterious liquid.
   GRILLED_PORK: Porky stock
   EGG: Egg Drop Soup

   



# -- Chat Distortion Settings --

# Text after specified commands will be distorted when drunk (list) [- /gl]
distortCommands:
- /gl
- /global
- /fl
- /s
- /letter

# Distort the Text written on a Sign while drunk [false]
distortSignText: false

# Enclose a text with these Letters to bypass Chat Distortion (Use "," as Separator) (list) [- '[,]']
distortBypass:
- '*,*'
- '[,]'

# words: Words and letters that will be altered when chatting while being drunk.
# Will be processed from first to last and a written sentece is altered in that order.

# replace: Word or letter to be replaced. (Special: "-space": replaces space, "-random": insert into random position, "-all": everything, "-start": At Beginning, "-end": At the End.)
# to: What to replace it with.
# pre: Words and Letters before the wanted word (split with ",")
# match: true = one of the "pre"-Words has to be before the wanted Word,  false = none of the "pre" Words is allowed before the wanted Word
# alcohol: 1-100 minimum drunkeness after which this word ist replaced
# percentage: Probability of replacing a Word in percent

words:
-  replace: s
   to: sh
   percentage: 90
   alcohol: 30

-  replace: ch
   to: sh
   pre: u,s,o,a
   match: false
   alcohol: 10
   percentage: 70

-  replace: h
   to: hh
   pre: sch,h,t
   match: false
   percentage: 60
   alcohol: 20

-  replace: th
   to: thl
   percentage: 40
   alcohol: 30

-  replace: sch
   to: shk
   percentage: 60
   alcohol: 40

-  replace: u
   to: uuh
   percentage: 20

-  replace: y
   to: yy
   percentage: 60
   alcohol: 15

-  replace: e
   to: ee
   percentage: 40
   alcohol: 15

-  replace: you
   to: u
   percentage: 40

-  replace: u
   to: uo
   pre: u
   match: false
   percentage: 60

-  replace: that
   to: taht
   percentage: 20
   alcohol: 40

-  replace: p
   to: b
   percentage: 30

-  replace: p
   to: b
   percentage: 70
   alcohol: 60

-  replace: up
   to: ubb
   percentage: 80
   alcohol: 25

-  replace: o
   to: oh
   percentage: 20

-  replace: ei
   to: i
   percentage: 30
   alcohol: 15

-  replace: b
   to: bb
   percentage: 80
   alcohol: 40

-  replace: '!!!'
   to: '!!!111!!!eleven!1!'
   pre: '!'
   match: false
   percentage: 20
   alcohol: 70

-  replace: '!'
   to: '!!'
   pre: '!'
   match: false
   percentage: 90

-  replace: drunk
   to: dhrkunn
   pre: are
   match: false
   percentage: 70
   alcohol: 65

-  replace: walk
   to: whhealhk
   pre: you can, you can still, you can not
   match: false
   percentage: 80
   alcohol: 30

-  replace: wtf
   to: wft
   percentage: 20
   alcohol: 40

-  replace: lol
   to: loool
   percentage: 80
   alcohol: 10

-  replace: afk
   to: aafkayyy
   percentage: 30
   alcohol: 30

-  replace: write
   to: wreitt
   pre: you can,you can still,you can not
   match: false
   percentage: 80
   alcohol: 50

-  replace: drink
   to: booze
   percentage: 80
   alcohol: 70

-  replace: '?'
   to: '????'
   pre: '?'
   match: false
   percentage: 80
   alcohol: 40

-  replace: -space
   to: ''
   pre: h,g,w
   match: true
   alcohol: 10

-  replace: -space
   to: ''
   percentage: 30
   alcohol: 35

-  replace: -space
   to: ''
   percentage: 10

-  replace: -start
   to: dho
   percentage: 15
   alcohol: 50

-  replace: -start
   to: hhn
   percentage: 10
   alcohol: 50

-  replace: -random
   to: lu
   percentage: 10

-  replace: -random
   to: lug
   percentage: 10
   alcohol: 50

-  replace: -random
   to: blub
   percentage: 20
   alcohol: 80

-  replace: -random
   to: lerg
   percentage: 40
   alcohol: 85

-  replace: -random
   to: gul
   percentage: 40
   alcohol: 80

-  replace: -random
   to: ' '
   percentage: 100
   alcohol: 70

-  replace: -random
   to: ' '
   percentage: 60
   alcohol: 40

-  replace: -random
   to: ' '
   percentage: 50
   alcohol: 30

-  replace: -end
   to: '!'
   percentage: 40
   alcohol: 30

-  replace: -random
   to: ' *hic* '
   percentage: 80
   alcohol: 70

-  replace: -random
   to: ' *hic* '
   percentage: 15
   alcohol: 40

-  replace: -space
   to: ' *hic* '
   percentage: 5
   alcohol: 20

-  replace: -end
   to: ' *hic*'
   percentage: 70
   alcohol: 50

-  replace: -all
   to: '*burp*'
   percentage: 3
   alcohol: 60

-  replace: -all
   to: '*burp*'
   percentage: 6
   alcohol: 80
